[book]
authors = ["The Funkin' Crew Inc.", "EliteMasterEric", "NxtVithor"]
language = "pt-br"
multilingual = false
src = "src"
title = "Friday Night Funkin' Documentação de Modding"


[output.html]
git-repository-url = "https://github.com/NxtVithor/funkin-modding-docs/tree/main/"
edit-url-template = "https://github.com/NxtVithor/funkin-modding-docs/edit/main/{path}"
